### ISSUE TITLE
Add the ability to duplicate a task

### ISSUE THREAD

**Issue by curtismayer** [MicroHealthLLC/mGis#1168] opened 2020-12-14 00:25 UTC
Requested by Marilyn Snyder ...

I would like the ability to duplicate a task – this is useful when we have similar tasks that repeat in future gates.

**Comment by LAlexMHllc** [comment] 2020-12-14 16:40
NOTE: Duplicate to Issue #1043

**Comment by bluenevus** [comment] 2020-12-14 19:38
duplicate of issue #1043

**Closed** 2021-02-08 15:32 UTC
Labels: Priority, enhancement
