### ISSUE TITLE
More consistent labels on tabs and form elements

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1690] opened 2021-02-08 16:41 UTC
Task forms - Task Category label and placeholder should be like Issues and Risks.
Risk forms - IDENTIFY tab should be RISK INFO; ASSIGN should be ASSIGNMENTS.
Screenshot Example

![forms_more_consistent_labels](https://user-images.githubusercontent.com/11938477/107251242-23523100-6a02-11eb-8349-7ffd5dc3fbd9.png)

**Comment by curtismayer** [comment] 2021-02-08 19:35
Throughout mGIS Task Category it will be moved to just Category.  As part of the update to Roles and Privileges and the Admin page in general, Category will be changed from being under Tasks to itself and designed such that a Category will be available to Tasks, Issues, Risks or maybe just 1 of them or just 2 and not all 3.

Additionally, Task, Issue, and Risk will not always be identical though they may reuse some functionality between all 3.  As a result, Risk has Assign in stead of Assignments to match the tense of the risk management process.  Risk is not Risk Info but is Identify because that is the first step of the risk management process, Identify the risk.

As such, this ticket is being closed as works as designed and some things being incorporated into upcoming designs.

**Closed by curtismayer** 2021-02-08 19:35 UTC
