### ISSUE TITLE
probability description under risks is a required field however there is no indicator

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1704] opened 2021-02-09 16:38 UTC
![image](https://user-images.githubusercontent.com/3675043/107395908-4268c580-6acb-11eb-84ae-a10e37d1804c.png)

**Comment by LAlexMHllc** [comment] 2021-02-09 16:42
Closing, since duplicate of Issue #1689

**Closed by LAlexMHllc** 2021-02-09 16:42 UTC
